"swagger": "2.0",
paths:
  /register:
    post:
      summary: Adds a new user
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                username:
                    type: string
                password:
                    type: string
              example:   # Sample object
                username: arg
                password: 123
      responses:
        '200':
          description: OK